config/routes.rb
Rails.application.routes.draw do
  get "login"     => "user_sessions#new",     :as => :login
  get "logout"    => "user_sessions#destroy", :as => :logout
  get "register"  => "users#new",             :as => :register

  get "shop"                        => "products#index"
  get "shop/our-coffee-portfolio"   => "products#index"
  get "shop/our-portfolio"          => "products#index"
  get "meet"                        => "pages#show",                                                :section_slug => "meet",      :page_slug => "snapshot"
  get "learn"                       => "pages#show",                                                :section_slug => "learn",     :page_slug => "the-muskoka-roastery-difference"
  get "sustain"                     => "pages#show",                                                :section_slug => "sustain",   :page_slug => "100-certified"
  get "contact"                     => "feedbacks#contact",           :as => :contact,              :section_slug => "none"
  get "company/contact-us"          => "feedbacks#contact",           :as => :contact_us,           :section_slug => "none"
  get "company/:page_slug"          => "pages#show",                  :as => :show_no_page,         :section_slug => "none"
  get "where-to-buy"                => "places#where_to_buy",         :as => :where_to_buy,         :section_slug => "none"
  get "places/where-to-buy-search"  => "places#where_to_buy_search",  :as => :where_to_buy_search

  get "blog"                                          => "blog_posts#index",      :as => :blog
  get "blog/category/:slug"                           => "blog_posts#category",   :as => :blog_category_show
  get "blog/:slug"                                    => "blog_posts#show",       :as => :blog_post_show
  get "blog_categories/:id/sort/:new_position"        => "blog_categories#sort",  :as => :blog_category_sort

  patch "pages/update_homepage_title"                 => "pages#update_homepage_title"
  put "pages/update_homepage_title"                   => "pages#update_homepage_title"
  get "pages/:id/sort/:new_position"                  => "pages#sort",            :as => :page_sort
  get "products/:id/sort/:new_position"               => "products#sort",         :as => :product_sort
  get "stay-connected"                                => "pages#connect"
  get "homepage1"                                     => "pages#homepage1"

  post "feedbacks/newsletter_signup" => "feedbacks#newsletter_signup", :as => :newsletter_signup

  get "products/:product_id/product_flavours/:id/sort/:new_position" => "product_flavours#sort", :as => :product_flavours_sort

  get "shopping_cart"                                 => "orders#show",                               :as => :current_order,  :id => "current"
  post "shopping_cart/add_discount"                   => "shopping_cart#add_discount",                :as => :add_discount
  get "shop/category/:slug"                           => "products#category",                         :as => :shop_category
  get "shop/categories"                               => "shopping_cart#categories",                  :as => :shop_categories
  get "shop/cart/:id"                                 => "shopping_cart#shopping_cart",               :as => :shop_cart
  post "shop/add_to_cart/:id"                         => "products#add_to_cart",                      :as => :add_product_to_cart
  get "shop/products/:slug"                           => "products#show",                             :as => :shop_product
  get "shop/empty_cart"                               => "shopping_cart#empty_cart",                  :as => :shop_empty_cart
  get "shop/checkout"                                 => "shopping_cart#checkout",                    :as => :shop_checkout
  get "shop/thankyou"                                 => "shopping_cart#thankyou",                    :as => :shop_thankyou
  get "shop/one_more_item/:id"                        => "shopping_cart#one_more_item",               :as => :shop_one_more_item
  get "shop/one_less_item/:id"                        => "shopping_cart#one_less_item",               :as => :shop_one_less_item
  get "shop/remove_item/:product_id/:option/:flavour" => "shopping_cart#remove_item",                 :as => :shop_remove_item
  post "shop/place_order"                             => "shopping_cart#place_order",                 :as => :shop_place_order
  post "shop/order_review_update_totals"              => "shopping_cart#order_review_update_totals",  :as => :order_review_update_totals
  get "shop/update_totals"                            => "shopping_cart#update_totals",               :as => :update_totals
  get "shop/submit_to_paypal/:id"                     => "shopping_cart#submit_to_paypal",            :as => :shop_submit_to_paypal

  resources :password_resets, :except => [:show, :index]
  resources :backgrounds
  resources :shipping_rates
  resources :discounts
  resources :documents
  resources :payment_notifications
  resources :line_items
  resources :orders
  resources :feedbacks
  resources :images do
    collection do
      get :browse
      post :upload
    end
  end
  resources :blog_categories
  resources :blog_posts
  resources :features do
    collection do
      put :update_left
      put :update_middle
      put :update_right
      get :edit_left
      get :edit_middle
      get :edit_right
    end
  end
  resources :pages do
    collection do
      get :edit_homepage_title
      put :update_homepage_title
    end
  end
  resources :product_types
  resources :products do
    collection do
      get :order
      put :sort
    end
    resources :product_flavours
  end
  resources :places
  resources :users
  resources :user_sessions

  get ":section_slug"             => "pages#show", :overview => true, :as => :show_section
  get ":section_slug/:page_slug"  => "pages#show",                    :as => :show_page

  root :to => "pages#homepage"

end

app/models/product_flavour.rb
class ProductFlavour < ActiveRecord::Base
  before_save :make_slug

  validates_presence_of :name

  belongs_to :product
  acts_as_list :scope => :product

  private

  def make_slug
    self.slug = self.name.parameterize
  end
end

app/controllers/product_flavours_controller.rb
class ProductFlavoursController < ApplicationController
  before_filter :require_admin
  before_filter :get_product

  def index
    @product_flavours = ProductFlavour.where(:product_id => @product.id).order(:product_id, :position)
  end

  def show
    @product_flavour = ProductFlavour.find(params[:id])
  end

  def sort
    flavour = ProductFlavour.find(params[:id])
    flavour.insert_at(params[:new_position])

    render :nothing => true
  end

  def new
    @product_flavour = ProductFlavour.new
  end

  def edit
    @product_flavour = ProductFlavour.find(params[:id])
  end

  def create
    @product_flavour = ProductFlavour.new(product_flavour_params)
    last_flavour = ProductFlavour.where(:product_id => @product.id).order(:position).last
    if last_flavour.present?
      @product_flavour.position = last_flavour.position + 1
    else
      @product_flavour.position = 1
    end
    @product_flavour.product_id = @product.id

    if @product_flavour.save
      redirect_to(product_product_flavours_path(@product), :notice => 'Product flavour was successfully created.')
    else
      render :action => "new"
    end
  end

  def update
    @product_flavour = ProductFlavour.find(params[:id])

    if @product_flavour.update(product_flavour_params)
      redirect_to(product_product_flavours_path(@product), :notice => 'Product flavour was successfully updated.')
    else
      render :action => "edit"
    end
  end

  def destroy
    @product_flavour = ProductFlavour.find(params[:id])
    @product_flavour.destroy

    redirect_to(product_product_flavours_url(@product))
  end

  private

  def get_product
    @product = Product.find(params[:product_id])
  end

  def product_flavour_params
    params.require(:product_flavour).permit(:name, :description, :position, :out_of_stock)
  end
end

app/helpers/product_flavours_helper.rb
module ProductFlavoursHelper
end

app/views/product_flavours/_form.html.haml
= simple_form_for [@product, @product_flavour] do |f|
  - if @product_flavour.errors.any?
    #error_explanation
      %h2
        = pluralize(@product_flavour.errors.count, "error")
        prohibited this flavour from being saved:

      %ul
      - @product_flavour.errors.full_messages.each do |msg|
        %li= msg

  .inputs
    / = f.input :product_id, :as => :hidden, :value => @product.id
    / = f.input :position, :as => :hidden, :value => @product_flavour.position
    = f.input :name
    = f.input :description, :as => :string
    = f.input :out_of_stock, :label => 'Out of stock?'

  .actions
    = f.button :submit

app/views/product_flavours/edit.html.haml
- content_for :title do
  Editing Flavour

= render 'form'

- content_for :sidebar do
  %p= link_to 'Show', product_product_flavour_path(@product, @product_flavour), :class => "feature-button"
  %br
  %p= link_to 'Destroy', product_product_flavour_path(@product, @product_flavour), :confirm => 'Are you sure?', :method => :delete
  %p= link_to 'Back', product_product_flavours_path(@product)

app/views/product_flavours/index.html.haml
- content_for :title do
  = "#{ @product.name }:"
  Flavours

- if @product_flavours.size == 0
  \- no flavours yet -
- else
  %ul{ :class => "sortable-flavours", 'data-product' => @product.id }
    - @product_flavours.each do |product_flavour|
      %li{ 'data-flavour' => product_flavour.id, :style => "border-top: 1px dotted #e0c298; padding-top: 10px;" }
        %span.handle &nbsp;
        %span{ :style => "margin-left: 5px; display: inline-block; width: 150px;" }= link_to product_flavour.name, product_product_flavour_path(@product, product_flavour)        
        %span{ :style => "display: inline-block; width: 470px;" }= product_flavour.description
        = link_to 'Edit', edit_product_product_flavour_path(@product, product_flavour)

  / %table.admin
  /   %tr
  /     %th
  /     %th Name
  /     %th Description
  /     %th
  /   - @product_flavours.each do |product_flavour|
  /     %tr{ :class => "#{ cycle('even', 'odd') }" }
  /       %td
  /         %span.handle &nbsp;
  /       %td{ :style => "width: 150px;" }= link_to product_flavour.name, product_product_flavour_path(@product, product_flavour)        
  /       %td= product_flavour.description
  /       %td{ :style => "padding-right: 10px;" }= link_to 'Edit', edit_product_product_flavour_path(@product, product_flavour)

- content_for :sidebar do
  .feature-sidebar    
    = link_to image_tag(@product.photo.url(:sidebar), :size => "164x97"), product_path(@product)
  %p= link_to 'New Flavour', new_product_product_flavour_path(@product), :class => "feature-button"
  %br
  %p= link_to 'Back to Product List', products_path

app/views/product_flavours/new.html.haml
- content_for :title do
  New Flavour

= render 'form'

- content_for :sidebar do
  %p= link_to 'Back', product_product_flavours_path(@product)

app/views/product_flavours/show.html.haml
- content_for :title do
  Showing Flavour

%p
  %b Name:
  = @product_flavour.name
%p
  %b Description:
  = @product_flavour.description
%p
  %b Slug:
  = @product_flavour.slug
%p
  %b Product:
  = @product_flavour.product.name
%p
  %b Position:
  = @product_flavour.position

- content_for :sidebar do
  %p= link_to 'Edit', edit_product_product_flavour_path(@product, @product_flavour), :class => "feature-button"
  %br
  %p= link_to 'Destroy', product_product_flavour_path(@product, @product_flavour), :confirm => 'Are you sure?', :method => :delete
  %p= link_to 'Back', product_product_flavours_path(@product)