config/routes.rb
Rails.application.routes.draw do
  get "login"     => "user_sessions#new",     :as => :login
  get "logout"    => "user_sessions#destroy", :as => :logout
  get "register"  => "users#new",             :as => :register

  get "shop"                        => "products#index"
  get "shop/our-coffee-portfolio"   => "products#index"
  get "shop/our-portfolio"          => "products#index"
  get "meet"                        => "pages#show",                                                :section_slug => "meet",      :page_slug => "snapshot"
  get "learn"                       => "pages#show",                                                :section_slug => "learn",     :page_slug => "the-muskoka-roastery-difference"
  get "sustain"                     => "pages#show",                                                :section_slug => "sustain",   :page_slug => "100-certified"
  get "contact"                     => "feedbacks#contact",           :as => :contact,              :section_slug => "none"
  get "company/contact-us"          => "feedbacks#contact",           :as => :contact_us,           :section_slug => "none"
  get "company/:page_slug"          => "pages#show",                  :as => :show_no_page,         :section_slug => "none"
  get "where-to-buy"                => "places#where_to_buy",         :as => :where_to_buy,         :section_slug => "none"
  get "places/where-to-buy-search"  => "places#where_to_buy_search",  :as => :where_to_buy_search

  get "blog"                                          => "blog_posts#index",      :as => :blog
  get "blog/category/:slug"                           => "blog_posts#category",   :as => :blog_category_show
  get "blog/:slug"                                    => "blog_posts#show",       :as => :blog_post_show
  get "blog_categories/:id/sort/:new_position"        => "blog_categories#sort",  :as => :blog_category_sort

  patch "pages/update_homepage_title"                 => "pages#update_homepage_title"
  put "pages/update_homepage_title"                   => "pages#update_homepage_title"
  get "pages/:id/sort/:new_position"                  => "pages#sort",            :as => :page_sort
  get "products/:id/sort/:new_position"               => "products#sort",         :as => :product_sort
  get "stay-connected"                                => "pages#connect"
  get "homepage1"                                     => "pages#homepage1"

  post "feedbacks/newsletter_signup" => "feedbacks#newsletter_signup", :as => :newsletter_signup

  get "products/:product_id/product_flavours/:id/sort/:new_position" => "product_flavours#sort", :as => :product_flavours_sort

  get "shopping_cart"                                 => "orders#show",                               :as => :current_order,  :id => "current"
  post "shopping_cart/add_discount"                   => "shopping_cart#add_discount",                :as => :add_discount
  get "shop/category/:slug"                           => "products#category",                         :as => :shop_category
  get "shop/categories"                               => "shopping_cart#categories",                  :as => :shop_categories
  get "shop/cart/:id"                                 => "shopping_cart#shopping_cart",               :as => :shop_cart
  post "shop/add_to_cart/:id"                         => "products#add_to_cart",                      :as => :add_product_to_cart
  get "shop/products/:slug"                           => "products#show",                             :as => :shop_product
  get "shop/empty_cart"                               => "shopping_cart#empty_cart",                  :as => :shop_empty_cart
  get "shop/checkout"                                 => "shopping_cart#checkout",                    :as => :shop_checkout
  get "shop/thankyou"                                 => "shopping_cart#thankyou",                    :as => :shop_thankyou
  get "shop/one_more_item/:id"                        => "shopping_cart#one_more_item",               :as => :shop_one_more_item
  get "shop/one_less_item/:id"                        => "shopping_cart#one_less_item",               :as => :shop_one_less_item
  get "shop/remove_item/:product_id/:option/:flavour" => "shopping_cart#remove_item",                 :as => :shop_remove_item
  post "shop/place_order"                             => "shopping_cart#place_order",                 :as => :shop_place_order
  post "shop/order_review_update_totals"              => "shopping_cart#order_review_update_totals",  :as => :order_review_update_totals
  get "shop/update_totals"                            => "shopping_cart#update_totals",               :as => :update_totals
  get "shop/submit_to_paypal/:id"                     => "shopping_cart#submit_to_paypal",            :as => :shop_submit_to_paypal

  resources :password_resets, :except => [:show, :index]
  resources :backgrounds
  resources :shipping_rates
  resources :discounts
  resources :documents
  resources :payment_notifications
  resources :line_items
  resources :orders
  resources :feedbacks
  resources :images do
    collection do
      get :browse
      post :upload
    end
  end
  resources :blog_categories
  resources :blog_posts
  resources :features do
    collection do
      put :update_left
      put :update_middle
      put :update_right
      get :edit_left
      get :edit_middle
      get :edit_right
    end
  end
  resources :pages do
    collection do
      get :edit_homepage_title
      put :update_homepage_title
    end
  end
  resources :product_types
  resources :products do
    collection do
      get :order
      put :sort
    end
    resources :product_flavours
  end
  resources :places
  resources :users
  resources :user_sessions

  get ":section_slug"             => "pages#show", :overview => true, :as => :show_section
  get ":section_slug/:page_slug"  => "pages#show",                    :as => :show_page

  root :to => "pages#homepage"

end

app/models/shopping_cart.rb
class ShoppingCart
  attr_reader :items, :promo_discount, :shipping, :discount_id, :order_id

  def initialize()
    # @items = options[:items] || []
    # @promo_discount = options[:promo_discount] || 0
    # @discount_id = options[:discount_id] || nil

    @items = []
    @promo_discount = 0
    @discount_id = nil
  end

  def set_promo_discount(percentage, id)
    @promo_discount = percentage
    @discount_id = id
  end

  def promo_discount_price
    # Go through each product in the list, check if the current discount counts towards it,
    # then generate the discount amount for that product * its quantity
    discount_price = 0
    discount = Discount.find(@discount_id) unless @discount_id.blank?

    if @promo_discount > 0
      @items.each do |item|
        if discount.products.exists?(:id => item.product.id)
          discount_price += item.price * @promo_discount / 100
        end
      end
    end

    return (discount_price * 100).to_i / 100.0 # Round to two decimal places
  end

  # def add_product(product)
  #   current_item = @items.find { |item| item.product == product }
  #   if current_item
  #     current_item.increment_quantity
  #   else
  #     current_item = ShoppingCartItem.new(product)
  #     @items.push current_item
  #   end
  #   return current_item
  # end

  def add_cart_item(product, quantity, option, flavour)
    current_item = @items.find { |item| item.product == product && item.option == option && item.flavour == flavour }
    if current_item
      current_item.add_to_quantity(quantity)
    else
      current_item = ShoppingCartItem.new(product, quantity, option, flavour)
      @items.push current_item
    end
    return current_item
  end

  def remove_product(product, option, flavour)
    item = @items.find { |i| i.product == product && i.option == option && i.flavour == flavour }
    item_index = @items.index(item)
    @items.delete_at(item_index)
    return item.item_id
  end

  def one_more(product)
    current_item = @items.find { |item| item.product == product }
    return current_item.increment_quantity
  end

  def one_less(product)
    current_item = @items.find { |item| item.product == product }
    return current_item.decrement_quantity
  end

  def total_items
    return @items.sum { |item| item.quantity }
  end

  def subtotal
    return @items.sum { |item| item.price }
  end

  def update_item_quantity(item_name, new_quantity)
    @items.each do |item|
      if item.item_id == item_name
        item.change_quantity(new_quantity)
        break
      end
    end
  end

  def total_price
    return subtotal - promo_discount_price
  end

end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController

  def check_promo
    @promo_discount = Discount.where({ :code => params[:code] }).first
    if @promo_discount && @promo_discount.expires_at > Time.now
      @cart.set_promo_discount(@promo_discount.id)
    end

    redirect_to shop_checkout_path
  end

  def remove_item
    product = Product.find(params[:product_id])
    @item_id = @cart.remove_product(product, params[:option], params[:flavour])

    respond_to do |format|
      format.html { redirect_back_or_default(shop_checkout_path) }
      format.js
    end
  end

  def one_more_item
    product = Product.find(params[:id])
    @cart.one_more(product)

    render :partial => "checkout_order"
  end

  def one_less_item
    product = Product.find(params[:id])
    @cart.one_less(product)

    render :partial => "checkout_order"
  end

  def add_discount
    @discount = Discount.where(:name => params[:code]).first
    if @discount && @discount.expires_at >= Time.now
      @cart = find_cart
      @cart.set_promo_discount(@discount.percentage, @discount.id)
    end

    redirect_to shop_checkout_path
  end

  def update_totals
    update_cart_quantities

    respond_to do |format|
      format.html { redirect_to_back(products_path) }
      format.js
    end
  end

  def order_review_update_totals
    update_cart_quantities
    find_estimated_country

    respond_to do |format|
      format.html { redirect_to_back(shop_checkout_path) }
      format.js
    end
  end

  def shopping_cart
    find_cart
  end

  def empty_cart
    session[:cart] = nil
    find_estimated_country

    respond_to do |format|
      format.html { redirect_to_back(products_path) }
      format.js
    end
  end

  def checkout
    update_cart_quantities
    find_estimated_country
    @order = Order.new
    @order.country = current_user.country if current_user
    @order.shipping_country = current_user.shipping_country if current_user
  end

  def place_order
    @order = Order.new(order_params)

    if @order.billing_same_as_shipping
      @order.shipping_country = @order.country
    end

    if @order.save
      @cart.items.each do |item|
        line_item = LineItem.new
        line_item.product_id = item.product.id
        line_item.order_id = @order.id
        line_item.quantity = item.quantity
        line_item.item_price = item.unit_price
        line_item.item_name = item.name
        line_item.item_option = item.option
        line_item.item_flavour = item.flavour
        line_item.save
      end
      @order.discount_percentage = @cart.promo_discount
      @order.discount_price = @cart.promo_discount_price
      @order.order_status_id = OrderStatus.where({ :name => "pending payment" }).first.id
      @order.save_shipping_costs # save out total calculations
      @order.save
      session[:cart] = nil # zero out shopping cart session

      # Check if user opted-in to newsletter and signup through Mailchimp's API if true.
      if @order.include_in_mailinglist
        # h = Hominid::API.new(Settings.mailchimp_api_key)
        # list_id = h.find_list_id_by_name(Settings.mailchimp_list_name)
        # # MailChimp API v1.3 method listSubscribe(string apikey, string id, string email_address, array merge_vars, string email_type, bool double_optin, bool update_existing, bool replace_interests, bool send_welcome)
        # h.list_subscribe(list_id, @order.email, { 'FNAME' => @order.split_name.first, 'LNAME' => @order.split_name.last }, 'html', false, true, true, false)

        api = Mailchimp::API.new(Settings.mailchimp_api_key)
        api.listSubscribe(id: Settings.mailchimp_list_id, email_address: params[:email_address])
      end

      respond_to do |format|
        format.html { redirect_to shop_submit_to_paypal_path(@order.id) }
        format.js
      end
    else
      render :action => "checkout"
    end
  end

  def submit_to_paypal
    @order = Order.find(params[:id])
  end

  def thankyou
    @reference_number = params[:order_id]
  end

  private

  def update_cart_quantities
    if params[:items]
      params[:items].each_pair do |key, value|
        @cart.update_item_quantity(key, value.to_i)
      end
    end
  end

  def find_estimated_country
    if client_country_code == "CA"
      @estimated_country = "Canadian"
    elsif client_country_code == "US"
      @estimated_country = "United States"
    else
      @estimated_country = "International"
    end
  end


  private

  def order_params
    params.require(:order).permit(:email, :address, :city, :province, :country,
      :postal, :phone, :total, :order_status_id, :purchased_at, :subtotal,
      :shipping_fees, :shipping_name, :free_shipping, :discount_percentage,
      :discount_price,
      :billing_same_as_shipping, :shipping_address, :shipping_city,
      :shipping_province, :shipping_country, :shipping_postal, :shipping_notes,
      :address_optional, :company, :shipping_address_optional, :shipping_phone,
      :name, :include_in_mailinglist)
  end

end

app/views/shopping_cart/_discount_form.html.haml
#discount-form-container
  If you have a promotional discount code, enter your code here:

  = form_tag add_discount_path, :class => "shop-form", :id => "discount-form" do
    %input{ :type => "text", :value => "", :name => "code", :placeholder => "Discount Code" }
    %input{ :type => "submit", :value => "Add" }

app/views/shopping_cart/_order_form.html.haml
.field
  .label
    = f.label :name, "Name"
    .hint Your full name.
  .input
    = f.text_field :name, :placeholder => "John Smith", :value => (current_user.name if current_user)
  .error
.field
  .label
    = f.label :company, "Company Name"
    .optional (optional)
    .hint If you are ordering for a business.
  .input
    = f.text_field :company, :placeholder => "Acme Corp.", :value => (current_user.company if current_user)
  .error
.field
  .label
    = f.label :email, "Email Address"
    .hint If we need to contact you.
  .input
    = f.text_field :email, :placeholder => "johnsmith@yourdomain.com", :value => (current_user.email if current_user)
  .error
.field
  .label
    = f.label :address, "Street Address"
    .hint Where your bills are delivered.
  .input
    = f.text_field :address, :placeholder => "123 Main Street", :value => (current_user.address if current_user)
  .error
.field
  .label
    = f.label :address_optional, "Apt., Suite, Bldg."
    .optional (optional)
    .hint Or any special instructions.
  .input
    = f.text_field :address_optional, :placeholder => "Apt. #345, South Bldg.", :value => (current_user.address_optional if current_user)
  .error
.field
  .label
    = f.label :city
    .hint Where you live.
  .input
    = f.text_field :city, :placeholder => "Toronto", :value => (current_user.city if current_user)
  .error
.field
  .label
    = f.label :province
    .hint Province, State, Territory, County.
  .input
    = f.text_field :province, :placeholder => "Ontario", :value => (current_user.province if current_user)
  .error
.field
  .label
    = f.label :country
    .hint Where you are in the world.
  .input
    = country_select "order", "country", ["Canada", "United States"] # Default value for this field is set in the controller on the @order model to make this work.
  .error
.field
  .label
    = f.label :postal, "Postal Code"
    .hint Post Code or ZIP
  .input
    = f.text_field :postal, :placeholder => "M6G 3B2", :value => (current_user.postal if current_user)
  .error
.field
  .label
    = f.label :phone, "Telephone Number"
    .hint Only used in case of delivery issues.
  .input
    = f.text_field :phone, :placeholder => "416.123.4567", :value => (current_user.phone if current_user)
  .error

app/views/shopping_cart/_order_review_item.html.haml
%td.thumbnail{ :width => 50 }
  .cart-item-wrapper
    = image_tag item.product.photo.url(:shopping_cart), :size => "40x40", :alt => "#{ item.name } Thumbnail"
%td.product-info
  .cart-item-wrapper
    - if item.flavour.blank? || item.flavour.downcase == "none"
      %h3=raw "#{ link_to item.name, product_path(item.product) }"
    - else
      %h3=raw "#{ link_to item.name, product_path(item.product) }: #{ item.flavour.titleize }"
    =raw "<strong>#{ item.option.titleize }</strong>"
    = "(#{ item.product.price_alt_txt })"
    %br
    = link_to "remove", shop_remove_item_path(item.product.id, item.option, item.flavour), :remote => true, :confirm => "Are you sure?"
%td.quantity{ :width => 40 }
  .cart-item-wrapper
    %input{ :type => "text", :value => item.quantity, :maxlength => 3, :name => "items[#{ item.item_id }]", :id => item.item_id }
%td.unit-price
  .cart-item-wrapper
    = number_to_currency item.unit_price
    ea.
%td.subtotal
  .cart-item-wrapper
    %h2= number_to_currency item.price

app/views/shopping_cart/_shipping_form.html.haml
.field
  .label
    = f.label :shipping_name, "Name"
    .optional (optional)
    .hint To whom you're shipping the coffee.
  .input
    = f.text_field :shipping_name, :placeholder => "Jane Smith", :value => (current_user.shipping_address if current_user)
  .error
.field
  .label
    = f.label :shipping_address, "Street Address"
    .hint Where the coffee should go.
  .input
    = f.text_field :shipping_address, :placeholder => "123 Main Street", :value => (current_user.shipping_address if current_user)
  .error
.field
  .label
    = f.label :shipping_address_optional, "Apt., Suite, Bldg."
    .optional (optional)
    .hint Or any special instructions.
  .input
    = f.text_field :shipping_address_optional, :placeholder => "Apt. #345, South Bldg.", :value => (current_user.shipping_address_optional if current_user)
  .error
.field
  .label
    = f.label :shipping_city
    .hint Where the coffee will be shipped.
  .input
    = f.text_field :shipping_city, :placeholder => "Toronto", :value => (current_user.shipping_city if current_user)
  .error
.field
  .label
    = f.label :shipping_province
    .hint Province, State, Territory, County.
  .input
    = f.text_field :shipping_province, :placeholder => "Ontario", :value => (current_user.shipping_province if current_user)
  .error
.field
  .label
    = f.label :shipping_country
    .hint Where in the world.
  .input
    = country_select "order", "shipping_country", ["Canada", "United States"] # Default value for this field is set in the controller on the @order model to make this work.
  .error
.field
  .label
    = f.label :shipping_postal, "Postal Code"
    .hint Post Code or ZIP
  .input
    = f.text_field :shipping_postal, :placeholder => "M6G 3B2", :value => (current_user.shipping_postal if current_user)
  .error
.field
  .label
    = f.label :shipping_phone, "Telephone Number"
    .hint Only used in case of delivery issues.
  .input
    = f.text_field :shipping_phone, :placeholder => "416.123.4567", :value => (current_user.shipping_phone if current_user)
  .error

app/views/shopping_cart/_shipping_rates.html.haml
-# TODO: It's not awesome that these variables are being defined in the view here...
- ca_rate = ShippingRate.where(:country_code => "CA").first
- us_rate = ShippingRate.where(:country_code => "US").first
- intl_rate = ShippingRate.where(:country_code => "INT").first
%p{ :style => "margin-bottom: 0;" }
  Our
  = link_to "shipping rates", "/company/shipping-rates"
  are:
%table.shipping-rates
  %tr
    %td $
    %td.currency
      %b= number_to_currency ca_rate.price, :unit => ""
    %td in Canada
  - if ca_rate.free_price > 0
    %tr.free-shipping
      %td{ :colspan => 3 }
        %i= "FREE for orders over #{ number_to_currency ca_rate.free_price }"
  %tr
    %td $
    %td.currency
      %b= number_to_currency us_rate.price, :unit => ""
    %td to the United States
  - if us_rate.free_price > 0
    %tr.free-shipping
      %td{ :colspan => 3 }
        %i= "FREE for orders over #{ number_to_currency us_rate.free_price }"
  %tr
    %td $
    %td.currency
      %b= number_to_currency intl_rate.price, :unit => ""
    %td
      for up to
      %b.light= DynamicSetting.find_by_name("shipping_rate_multiple").value.to_i
      units Int'l
  - if intl_rate.free_price > 0
    %tr.free-shipping
      %td{ :colspan => 3 }
        %i= "FREE for orders over #{ number_to_currency intl_rate.free_price }"
  / %tr
  /   %td
  /   %td.currency
  /     %b FREE
  /   %td
  /     for orders in Canada over $40
  /     -# TODO: Make this value dynamic.

  -# %br
  -# %b.light= number_to_currency ShippingRate.where(:country_code => "CA").first.price
  -# in Canada
  -# %br
  -# %b.light= number_to_currency ShippingRate.where(:country_code => "US").first.price
  -# to the United States
  -# %br
  -# %b.light= number_to_currency ShippingRate.where(:country_code => "INT").first.price
  -# for up to
  -# %b.light= DynamicSetting.find_by_name("shipping_rate_multiple").value
  -# units Int'l
  -# , and for every
  -# %b.light= DynamicSetting.find_by_name("shipping_rate_multiple").value
  -# units thereafter.

app/views/shopping_cart/_small_cart.html.haml
%h3#shopping-cart-total-title
  = @cart.total_items
  - if @cart.total_items == 1
    Item
  - else
    Items
%h2 Shopping Cart
%p
  Browse through our shop, find the coffee you're looking for, indicate a quantity
  next to the type you like, and click the 'Add to Cart' button.
%br
= render :partial => "shopping_cart/shipping_rates"

#shopping-cart-form-holder
  = form_tag shop_checkout_path, :method => :get, :class => "shop-form shopping-cart", :id => "shopping-cart-form", :style => "#{ "display: none;" unless @cart && @cart.items.size > 0 }" do
    %ul#cart-items.clearfix
      - if @cart && @cart.items.size > 0
        - @cart.items.each do |item|
          %li.clearfix.cart-item-container{ :id => "cart-#{ item.item_id  }" }
            = render :partial => "shopping_cart/small_cart_line_item", :locals => { :item => item }
      -# %li#cart-subtotal-container.shopping-cart-subtotal.clearfix
      -#   = render :partial => "shopping_cart/small_cart_subtotal", :locals => { :cart => @cart, :estimated_shipping_fees => @estimated_shipping_fees }
      %li#cart-total-container.shopping-cart-total.clearfix
        = render :partial => "shopping_cart/small_cart_total", :locals => { :cart => @cart, :estimated_shipping_fees => @estimated_shipping_fees }
      -# = render :partial => "shopping_cart/small_cart_shipping_rates"
    = submit_tag "Review Order", :style => "margin-bottom: 10px;"
    or
    = link_to "empty cart", shop_empty_cart_path, :remote => true
    - if @cart && @cart.items.size > 0
      - content_for :scripts do
        = javascript_include_tag :validate_shopping_cart
  #empty-cart-container{ :style => "#{ "display: none;" if @cart && @cart.items.size > 0 }" }
    %br
    %b (your shopping cart is empty)

app/views/shopping_cart/_small_cart_line_item.html.haml
.shopping-cart-item-name
  %h3= link_to item.product.name, shop_product_path(item.product.slug)
  - unless item.flavour == "none"
    %b= item.flavour.titleize
.left.thumbnail
  = link_to image_tag(item.product.photo.url(:shopping_cart), :size => '40x40', :alt => item.product.name), shop_product_path(item.product.slug)
.right.info
  = item.option.titleize
  %br
  = "#{ number_to_currency item.unit_price } #{ item.product.per }"
  %br
  .shopping-cart-item-quantity.clearfix
    .left
      Qty
      %input{ :type => "text", :size => 2, :name => "items[#{ item.item_id }]", :id => item.item_id, :value => item.quantity }
    .right
      = number_to_currency item.price

app/views/shopping_cart/_small_cart_total.html.haml
.left 
  Total
.right
  -# %h2#cart-total-price= number_to_currency cart.total_price + estimated_shipping_fees
  %h2#cart-total-price= number_to_currency cart.total_price
  = link_to "update totals", "#", :id => "update-totals-link"

app/views/shopping_cart/checkout.html.haml
- content_for :title do
  Place Your Order

- unless current_user
  %p{ :style => "font-weight: bold;" }
    If you have already
    = link_to "registered an account", new_user_path
    with us, you can
    = link_to "login", login_path(:d => 'checkout')
    to sync your account details with your shopping cart.
%p
  Check that your order details exactly what you are expecting to purchase. If you want to make
  a change or add an item, you can still go back and
  =raw "#{ link_to "continue shopping", products_path }."
  Once your order looks good, and you have entered your billing and shipping information, proceed to checkout.
  If you encounter any problems at any point during the purchasing process, please let us know at
  = link_to Settings.support_email, "mailto:#{ Settings.support_email }"
%p
  %b ***Please note that due to the potential Canada Post strike we are unable to ship orders to any Canadian P.O box***
%p
  = render :partial => "shopping_cart/shipping_rates"

-# = render :partial => "discount_form"

#order-review
  = render :partial => "order_review"

#order-form-container
  - if @cart && @cart.items.size > 0
    = form_for @order,
      :url => shop_place_order_path,
      :remote => true,
      :html => { :class => "muskoka-form", :id => "order-form", :method => :post } do |f|

      -# = f.hidden_field :total, :value => @cart.subtotal
      -# = f.hidden_field :order_status_id, :value => @default_order_status.id
      = f.error_messages

      #billing-details
        %h2 Billing Details
        %p
          If your billing and shipping details are the same, then please fill out this single form. If
          your shipping address is different from your billing address, simply un-check the box at the
          bottom to reveal the separate shipping details form.

        = render :partial => "order_form", :locals => { :f => f }

        .field
          .long
            = f.check_box :include_in_mailinglist, :checked => (current_user.include_in_mailinglist if current_user)
            %b= Settings.mailing_list_label
            .hint
              = Settings.mailing_list_description
        .field
          .long
            = f.check_box :billing_same_as_shipping, :checked => (current_user ? current_user.billing_same_as_shipping : 'checked')
            %b shipping address is the same as billing address
            .hint
              If your shipping address is different than your billing
              address, simply uncheck this box.

        / #billing-button.actions.clearfix
        /   .button
        /     = f.submit "Check Out", :id => "billing-button-button"
        /   .extras
        /     or
        /     = link_to "continue shopping", products_path
        / #billing-loader.actions.clearfix
        /   .button.loading
        /     Connecting to PayPal. Please wait.

      #shipping-details.clearfix
        %h2 Shipping Details
        %p
          When you are sending the coffee in a different direction, please fill out the information
          below so that we get the coffee to the right destination.

        = render :partial => "shipping_form", :locals => { :f => f }

      #checkout-button.actions.clearfix
        .button
          = f.submit "Check Out", :id => "checkout-button-button"
        .extras
          or
          = link_to "continue shopping", products_path
      #checkout-loader.actions.clearfix
        .button.loading
          Connecting to PayPal. Please wait.

%p
  Your privacy is important to us. Your billing and shipping information is used only for the purposes
  of fulfilling your order (sending a bill and shipping your coffee to where you want it to go). Some
  circumstances may require that we contact you in order to fulfill your order, and we may need your
  phone number in this case, but only in the interest of getting you your coffee. Please read our full
  = link_to "terms of use", "/company/terms-of-use"
  if you have any concerns.
  
= render "floodlight_tags/checkout"

- content_for :scripts do
  = javascript_include_tag :select_skin
  = javascript_include_tag :validate_order

app/views/shopping_cart/place_order.js.erb
$("#order-review").after("<div id='paypal-form-container' style='display: none;'></div>");
$("#paypal-form-container").html("<%= escape_javascript(render(:partial => "shopping_cart/paypal_form", :locals => { :order => @order })) %>");
$("#paypal-form").submit();

app/views/shopping_cart/remove_item.js.erb
$("#cart-<%= @item_id %> .cart-item-wrapper").slideUp("fast", function() {
  $("#cart-<%= @item_id %>").remove();
});

$("#order-review-subtotal-price").html("<%= number_to_currency @cart.subtotal %>");
$("#order-review-total-price").html("<%= number_to_currency @cart.total_price + @estimated_shipping_fees %>");

<% if @cart.total_items == 0 %>
    $("#order-review-shipping-price").html("<%= number_to_currency 0 %>");
  $("#global-total-items").html("0");
  $("#global-price-total").html("$0.00");
  $("#global-checkout-button").addClass("empty");
<% else %>
  $("#order-review-shipping-price").html("<%= number_to_currency @estimated_shipping_fees %>");
  $("#global-total-items").html("<%= @cart.total_items %>");
  $("#global-price-total").html("<%= number_to_currency @cart.total_price + @estimated_shipping_fees %>");
<% end %>

app/views/shopping_cart/submit_to_paypal.html.haml
- if @order.order_status.name == "paid"
  - content_for :title do
    Order Paid
  %p
    The order you are looking for has already been paid.
- else
  - content_for :title do
    Proceed to Make Payment
  %p
    If you are not redirected automatically within the next few seconds, please click the button below to proceed
    to PayPal and complete your order.
  #paypal-form-container
    = render :partial => "paypal_form", :locals => { :order => @order }

app/views/shopping_cart/thankyou.html.haml
- content_for :title do
  Thank you

%p
  Your order was successfully completed. 
  - if @reference_number
    Your reference number is:
    %b{ :style => "font-size: 16px;" }= @reference_number
%p
  Once your order is placed, the Muskoka Roastery will handcraft your coffee within 2 business days and ship it 
  to you by Canada Post. Approximate delivery times are: Ontario (2-3 days), balance of Canada (3-5 days), USA (6 days) 
  and International (6-8 weeks).
%p
  If you have any questions or concerns about your order, please feel free to
  =raw link_to "contact us", "/company/contact-us"
  at any time and cite your reference number. We will be happy to help you in whatever way we can.

= render "floodlight_tags/thank_you"

app/views/shopping_cart/update_totals.js.erb
$("#shopping-cart-container").html("<%= escape_javascript(render(:partial => "shopping_cart/small_cart")) %>");
$("#shopping-cart").html("<%= escape_javascript(render(:partial => "layouts/shopping_cart")) %>");
$("#update-totals-link").show();
$("#update-totals-link").click(function(event) {
  var form = $("#shopping-cart-form");
  event.preventDefault();
  $.post("/shop/update_totals", form.serialize(), null, "script");
  return false;
});