config/routes.rb
Rails.application.routes.draw do
  get "login"     => "user_sessions#new",     :as => :login
  get "logout"    => "user_sessions#destroy", :as => :logout
  get "register"  => "users#new",             :as => :register

  get "shop"                        => "products#index"
  get "shop/our-coffee-portfolio"   => "products#index"
  get "shop/our-portfolio"          => "products#index"
  get "meet"                        => "pages#show",                                                :section_slug => "meet",      :page_slug => "snapshot"
  get "learn"                       => "pages#show",                                                :section_slug => "learn",     :page_slug => "the-muskoka-roastery-difference"
  get "sustain"                     => "pages#show",                                                :section_slug => "sustain",   :page_slug => "100-certified"
  get "contact"                     => "feedbacks#contact",           :as => :contact,              :section_slug => "none"
  get "company/contact-us"          => "feedbacks#contact",           :as => :contact_us,           :section_slug => "none"
  get "company/:page_slug"          => "pages#show",                  :as => :show_no_page,         :section_slug => "none"
  get "where-to-buy"                => "places#where_to_buy",         :as => :where_to_buy,         :section_slug => "none"
  get "places/where-to-buy-search"  => "places#where_to_buy_search",  :as => :where_to_buy_search

  get "blog"                                          => "blog_posts#index",      :as => :blog
  get "blog/category/:slug"                           => "blog_posts#category",   :as => :blog_category_show
  get "blog/:slug"                                    => "blog_posts#show",       :as => :blog_post_show
  get "blog_categories/:id/sort/:new_position"        => "blog_categories#sort",  :as => :blog_category_sort

  patch "pages/update_homepage_title"                 => "pages#update_homepage_title"
  put "pages/update_homepage_title"                   => "pages#update_homepage_title"
  get "pages/:id/sort/:new_position"                  => "pages#sort",            :as => :page_sort
  get "products/:id/sort/:new_position"               => "products#sort",         :as => :product_sort
  get "stay-connected"                                => "pages#connect"
  get "homepage1"                                     => "pages#homepage1"

  post "feedbacks/newsletter_signup" => "feedbacks#newsletter_signup", :as => :newsletter_signup

  get "products/:product_id/product_flavours/:id/sort/:new_position" => "product_flavours#sort", :as => :product_flavours_sort

  get "shopping_cart"                                 => "orders#show",                               :as => :current_order,  :id => "current"
  post "shopping_cart/add_discount"                   => "shopping_cart#add_discount",                :as => :add_discount
  get "shop/category/:slug"                           => "products#category",                         :as => :shop_category
  get "shop/categories"                               => "shopping_cart#categories",                  :as => :shop_categories
  get "shop/cart/:id"                                 => "shopping_cart#shopping_cart",               :as => :shop_cart
  post "shop/add_to_cart/:id"                         => "products#add_to_cart",                      :as => :add_product_to_cart
  get "shop/products/:slug"                           => "products#show",                             :as => :shop_product
  get "shop/empty_cart"                               => "shopping_cart#empty_cart",                  :as => :shop_empty_cart
  get "shop/checkout"                                 => "shopping_cart#checkout",                    :as => :shop_checkout
  get "shop/thankyou"                                 => "shopping_cart#thankyou",                    :as => :shop_thankyou
  get "shop/one_more_item/:id"                        => "shopping_cart#one_more_item",               :as => :shop_one_more_item
  get "shop/one_less_item/:id"                        => "shopping_cart#one_less_item",               :as => :shop_one_less_item
  get "shop/remove_item/:product_id/:option/:flavour" => "shopping_cart#remove_item",                 :as => :shop_remove_item
  post "shop/place_order"                             => "shopping_cart#place_order",                 :as => :shop_place_order
  post "shop/order_review_update_totals"              => "shopping_cart#order_review_update_totals",  :as => :order_review_update_totals
  get "shop/update_totals"                            => "shopping_cart#update_totals",               :as => :update_totals
  get "shop/submit_to_paypal/:id"                     => "shopping_cart#submit_to_paypal",            :as => :shop_submit_to_paypal

  resources :password_resets, :except => [:show, :index]
  resources :backgrounds
  resources :shipping_rates
  resources :discounts
  resources :documents
  resources :payment_notifications
  resources :line_items
  resources :orders
  resources :feedbacks
  resources :images do
    collection do
      get :browse
      post :upload
    end
  end
  resources :blog_categories
  resources :blog_posts
  resources :features do
    collection do
      put :update_left
      put :update_middle
      put :update_right
      get :edit_left
      get :edit_middle
      get :edit_right
    end
  end
  resources :pages do
    collection do
      get :edit_homepage_title
      put :update_homepage_title
    end
  end
  resources :product_types
  resources :products do
    collection do
      get :order
      put :sort
    end
    resources :product_flavours
  end
  resources :places
  resources :users
  resources :user_sessions

  get ":section_slug"             => "pages#show", :overview => true, :as => :show_section
  get ":section_slug/:page_slug"  => "pages#show",                    :as => :show_page

  root :to => "pages#homepage"

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  validates_presence_of :name, :email, :comment
  validates_length_of :name, :minimum => 2
  validates :email, :format => /([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})/i

  def split_name
    @splited_name ||= name.split
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_filter :require_admin, :except => [:new, :create, :contact, :newsletter_signup]

  def index
    @feedbacks = Feedback.order("created_at desc").page(params[:page]).per(20)
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  def new
    @feedback = Feedback.new
  end

  def contact
    @section = Section.where(:slug => "none").first()
    @featured_product = Feature.where(:is_active => true).first()
    contact_page_id = DynamicSetting.find_by_name("contact_page_id").value.to_i
    @page = Page.find(contact_page_id)
    @feedback = Feedback.new
  end

  def newsletter_signup
    api = Mailchimp::API.new(Settings.mailchimp_api_key)
    if params[:email_address] && api.listSubscribe(id: Settings.mailchimp_list_id, email_address: params[:email_address])
      h = Hominid::API.new(Settings.mailchimp_api_key)
      list_id = h.find_list_id_by_name(Settings.mailchimp_list_name)
      h.list_subscribe(list_id, params[:email_address], {}, 'html', false, true, true, false)

      render :nothing => true, :status => :ok, :layout => false
    else

      render :nothing => true, :status => :unprocessable_entity, :layout => false
    end
  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def create
    contact_page_id = DynamicSetting.find_by_name("contact_page_id").value.to_i
    @page = Page.find(contact_page_id)
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        FeedbackMailer.contact(@feedback).deliver

        # Check if user opted-in to newsletter and signup through Mailchimp's API if true.
        if @feedback.include_in_mailinglist
          api = Mailchimp::API.new(Settings.mailchimp_api_key)
          api.listSubscribe(id: Settings.mailchimp_list_id, email_address: params[:email_address])

          # h = Hominid::API.new(Settings.mailchimp_api_key)
          # list_id = h.find_list_id_by_name(Settings.mailchimp_list_name)
          # # MailChimp API v1.3 method listSubscribe(string apikey, string id, string email_address, array merge_vars, string email_type, bool double_optin, bool update_existing, bool replace_interests, bool send_welcome)
          # h.list_subscribe(list_id, @feedback.email, { 'FNAME' => @feedback.split_name.first, 'LNAME' => @feedback.split_name.last }, 'html', false, true, true, false)
        end

        format.html { redirect_to "/contact", :notice => 'Thank you. Your feedback was successfully sent.' }
        format.js
      else
        format.html { render :action => "contact" }
        format.js
      end
    end
  end

  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to(@feedback, :notice => 'Feedback was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @feedback.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to(feedbacks_url) }
      format.xml  { head :ok }
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(:name, :email, :website, :comment,
      :include_in_mailinglist)
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_create.html.haml
= form_for @feedback, :remote => true, :html => { :class => "muskoka-form", :id => "contact-form" } do |f|
  -if @feedback.errors.any?
    #error_explanation
      %h2= "#{ pluralize(@feedback.errors.count, "error") } prohibited your feedback from being saved:"
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg

  .field
    .label
      = f.label :name
      .hint So we can say hello.
    .input= f.text_field :name, :placeholder => "John Smith"
    .error 
  .field
    .label
      = f.label :email
      .hint So we can reply back to you.
    .input= f.text_field :email, :placeholder => "johnsmith@yourdomain.com"
    .error  
  .field
    .label
      = f.label :comment, "Message"
      .hint
        Ask us a question, give us feedback on how
        we can make your experience better, or just say hello.
    .input= f.text_area :comment, :placeholder => "Your message..."
    .error
  .field
    .long
      = f.check_box :include_in_mailinglist
      %b= Settings.mailing_list_label      
      .hint
        = Settings.mailing_list_description
  .actions
    = f.submit "Send"

app/views/feedbacks/_form.html.haml
= simple_form_for @feedback do |f|
  = f.error_messages
  = f.input :name
  = f.input :email
  = f.input :comment, :input_html => { :class => "medium" }
  = f.button :submit

app/views/feedbacks/_thankyou.html.haml
#success_explanation
  %h2 Thank you for your feedback
  %p
    If your message calls for a response from us, we try to reply within 5 business days.
%p{ :style => "padding-top: 20px;" }
  Got something else to say?
  = link_to "Write us another message", contact_path

app/views/feedbacks/contact.html.haml
- content_for :title do
  = @page.name

#intro
  =raw @page.intro

=raw @page.body

#contact-form-container
  = render :partial => "create"

.loading
  Sending. Please wait.

- content_for :sidebar do
  - unless @featured_product.blank?
    %h3 Featured
    .feature-sidebar
      = render :partial => "pages/feature", :locals => { :feature => @featured_product }
  - if current_user and current_user.is_admin?
    %p= link_to 'Edit Page', edit_page_path(@page), :class => "feature-button"
    %br
    - if @page.slug != "blog"
      %p= link_to 'Destroy', page_path(@page), :confirm => "Are you sure?", :method => :delete

- unless @page.description.blank?
  - content_for :description do
    = @page.description
- unless @page.keywords.blank?
  - content_for :keywords do
    = @page.keywords

- content_for :scripts do
  = javascript_include_tag :validate_contact

= render "floodlight_tags/contact_us"

app/views/feedbacks/create.js.erb
$(".loading").hide();
$("#contact-form-container").html("<%= escape_javascript(render(:partial => "thankyou")) %>");

app/views/feedbacks/edit.html.haml
- content_for :title do
  Editing feedback

= render 'form'

- content_for :sidebar do
  %p= link_to 'Show', @feedback, :class => "feature-button"
  %p= link_to 'Back', feedbacks_path

app/views/feedbacks/form.html.erb
<form accept-charset="UTF-8" action="/feedbacks" class="simple_form feedback" id="new_feedback" method="post">
  <div style="margin:0;padding:0;display:inline">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input name="authenticity_token" type="hidden" value="ljFwEhOTu34tS+hQrflShilKzoyOQH0Jy8PPxGrN/Qw=" />
  </div>

  <div class="input string required">
    <label class="string required" for="feedback_name">
      <abbr title="required">*</abbr>
      Name
    </label>
    <input class="string required" id="feedback_name" maxlength="255" name="feedback[name]" required="required" size="50" type="text" />
    <span class="hint">So we can refer to you appropriately.</span>
  </div>

  <div class="input string email optional"><label class="email optional" for="feedback_email"> Email Address</label><input class="string email optional" id="feedback_email" maxlength="255" name="feedback[email]" size="50" type="email" /><span class="hint">So we can reply back to you.</span></div>
  <div class="input text optional"><label class="text optional" for="feedback_comment"> Message</label><textarea class="text optional" cols="40" id="feedback_comment" name="feedback[comment]" rows="20"></textarea><span class="hint">Tell us a story about yourself, ask us a question, give us feedback onhow we can makeyour experience better, or just say hello.</span></div>
  <input class="button" id="feedback_submit" name="commit" type="submit" value="Create Feedback" />
</form>


<form accept-charset="UTF-8" action="/pages/15" class="simple_form page" id="edit_page_15" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="_method" type="hidden" value="put" /><input name="authenticity_token" type="hidden" value="l2e14PSAyd09SDxXDvoQLx7sBa/4CZMUymqBDKF+/Zg=" /></div>

  <div class="error-messages">
    <h2>Invalid Fields</h2>
    <p>Correct the following errors and try again.</p>
    <ul>
      <li>Name can't be blank</li>
    </ul>
  </div>

  <div class="input string required field_with_errors">
    <label class="string required" for="page_name">
      <abbr title="required">*</abbr>
      Page Title
    </label>
    <input class="string required" id="page_name" maxlength="255" name="page[name]" required="required" size="50" type="text" value="" />
    <span class="error">can't be blank</span>
  </div>
            <div class='editor-area'>
              <textarea class="tinymce small" cols="40" id="page_intro" name="page[intro]" rows="20">&lt;p&gt;We are continually surprised by the amount of mis-information out there on the fairly straight-forward subject of how to store coffee.&lt;/p&gt;</textarea>
            </div>
            <div class='editor-area'>
              <textarea class="tinymce" cols="40" id="page_body" name="page[body]" rows="20">&lt;p&gt;The scientific facts are not in dispute- exposure to oxygen, moisture, sunlight and heat will cause your coffee to stale over time. Ground coffee is more susceptible than whole beans, simply because there is more surface area exposed to the elements.&lt;/p&gt;&#x000A;&lt;p&gt;Our coffee is sold in a bag which provides a barrier that will not allow any of these elements to come into contact with the product before opening. So, the following storage tips relate to the coffee once opened.&lt;/p&gt;&#x000A;&lt;ul&gt;&#x000A;&lt;li&gt; &lt;strong&gt;Store at room temperature&lt;/strong&gt;,&amp;nbsp;not over a heat source or in the refrigerator or in the freezer. &lt;/li&gt;&#x000A;&lt;li&gt; &lt;strong&gt;Keep the product in the Muskoka Roastery bag&lt;/strong&gt; and fold the top down tightly to eliminate as much air from the pack as possible. Use the tin tie and/or wrap an elastic band around the rolled bag. &lt;/li&gt;&#x000A;&lt;li&gt; &lt;strong&gt;Put the bag in a ceramic storage container&lt;/strong&gt;,&amp;nbsp;ideally not much bigger than the bag.&lt;/li&gt;&#x000A;&lt;/ul&gt;&#x000A;&lt;p&gt;If you don&amp;rsquo;t use 1lb of coffee within a 2 week period, we suggest that you exclusively buy whole beans and purchase a grinder or &amp;lsquo;bean to cup&amp;rsquo; machine with an integrated grinder to extend the product freshness as long as possible.&lt;/p&gt;</textarea>
            </div>
            <div class="input radio required"><label class="radio required" for="page_section_id"><abbr title="required">*</abbr> Section</label><label class="collection_radio" for="page_section_id_1"><input class="radio required" id="page_section_id_1" name="page[section_id]" required="required" type="radio" value="1" />Meet</label><label class="collection_radio" for="page_section_id_2"><input checked="checked" class="radio required" id="page_section_id_2" name="page[section_id]" required="required" type="radio" value="2" />Learn</label><label class="collection_radio" for="page_section_id_3"><input class="radio required" id="page_section_id_3" name="page[section_id]" required="required" type="radio" value="3" />Shop</label><label class="collection_radio" for="page_section_id_4"><input class="radio required" id="page_section_id_4" name="page[section_id]" required="required" type="radio" value="4" />Sustain</label><label class="collection_radio" for="page_section_id_5"><input class="radio required" id="page_section_id_5" name="page[section_id]" required="required" type="radio" value="5" />Blog</label><label class="collection_radio" for="page_section_id_6"><input class="radio required" id="page_section_id_6" name="page[section_id]" required="required" type="radio" value="6" />None</label></div>
            <div class="input string optional"><label class="string optional" for="page_keywords"> Keywords</label><input class="string optional" id="page_keywords" maxlength="255" name="page[keywords]" size="50" type="text" value="" /></div>
            <div class="input string optional"><label class="string optional" for="page_description"> Description</label><input class="string optional" id="page_description" maxlength="255" name="page[description]" size="50" type="text" value="" /></div>
            <input class="button" id="page_submit" name="commit" type="submit" value="Update Page" />
          </form>

<form accept-charset="UTF-8" action="/feedbacks" class="simple_form feedback" id="new_feedback" method="post"><div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="&#x2713;" /><input name="authenticity_token" type="hidden" value="ljFwEhOTu34tS+hQrflShilKzoyOQH0Jy8PPxGrN/Qw=" /></div>

  <div class="input string required">
    <label class="string required" for="feedback_name"><abbr title="required">*</abbr> Name</label>
    <div class="hint">So we can refer to you appropriately.</div>
    <input class="string required" id="feedback_name" maxlength="255" name="feedback[name]" required="required" size="50" type="text" />
    <div class="error">Something went wrong</div>
  </div>

<div class="input string email optional"><label class="email optional" for="feedback_email"> Email Address</label><div class="hint">So we can reply back to you.</div><input class="string email optional" id="feedback_email" maxlength="255" name="feedback[email]" size="50" type="email" /></div>
  <div class="input text optional"><label class="text optional" for="feedback_comment"> Message</label><div class="hint">Tell us a story about yourself, ask us a question, give us feedback onhow we can makeyour experience better, or just say hello.</div><textarea class="text optional" cols="40" id="feedback_comment" name="feedback[comment]" rows="20"></textarea></div>
  <input class="button" id="feedback_submit" name="commit" type="submit" value="Create Feedback" />
</form>

<%= tinymce %>

app/views/feedbacks/index.html.haml
- content_for :title do
  Latest Feedback

%table.admin{ :style => "width: 100%" }
  %tr
    %th Name
    %th Email
    %th Date
    %th
    %th
    %th

  - @feedbacks.each do |feedback|
    %tr{ :class => "#{ cycle("even", "odd") }" }
      %td= feedback.name
      %td= feedback.email
      %td= feedback.created_at.strftime("%e %B %Y @%l:%M%P")
      %td= link_to 'Show', feedback
      %td= link_to 'Edit', edit_feedback_path(feedback)
      %td= link_to 'Destroy', feedback, :confirm => 'Are you sure?', :method => :delete
%hr
= paginate @feedbacks

-# - content_for :sidebar do
-#   %p= link_to 'New Feedback', new_feedback_path, :class => "feature-button"

app/views/feedbacks/new.html.haml
%h1 New feedback

= render 'form'

= link_to 'Back', feedbacks_path

app/views/feedbacks/show.html.haml
- content_for :title do
  Showing Feedback

%p
  %b Name:
  = @feedback.name
%p
  %b Email:
  = @feedback.email
%p
  %b Comment:
  = @feedback.comment

- content_for :sidebar do
  %p= link_to 'Edit', edit_feedback_path(@feedback), :class => "feature-button"
  %p= link_to 'Back', feedbacks_path