config/routes.rb
Rails.application.routes.draw do
  get "login"     => "user_sessions#new",     :as => :login
  get "logout"    => "user_sessions#destroy", :as => :logout
  get "register"  => "users#new",             :as => :register

  get "shop"                        => "products#index"
  get "shop/our-coffee-portfolio"   => "products#index"
  get "shop/our-portfolio"          => "products#index"
  get "meet"                        => "pages#show",                                                :section_slug => "meet",      :page_slug => "snapshot"
  get "learn"                       => "pages#show",                                                :section_slug => "learn",     :page_slug => "the-muskoka-roastery-difference"
  get "sustain"                     => "pages#show",                                                :section_slug => "sustain",   :page_slug => "100-certified"
  get "contact"                     => "feedbacks#contact",           :as => :contact,              :section_slug => "none"
  get "company/contact-us"          => "feedbacks#contact",           :as => :contact_us,           :section_slug => "none"
  get "company/:page_slug"          => "pages#show",                  :as => :show_no_page,         :section_slug => "none"
  get "where-to-buy"                => "places#where_to_buy",         :as => :where_to_buy,         :section_slug => "none"
  get "places/where-to-buy-search"  => "places#where_to_buy_search",  :as => :where_to_buy_search

  get "blog"                                          => "blog_posts#index",      :as => :blog
  get "blog/category/:slug"                           => "blog_posts#category",   :as => :blog_category_show
  get "blog/:slug"                                    => "blog_posts#show",       :as => :blog_post_show
  get "blog_categories/:id/sort/:new_position"        => "blog_categories#sort",  :as => :blog_category_sort

  patch "pages/update_homepage_title"                 => "pages#update_homepage_title"
  put "pages/update_homepage_title"                   => "pages#update_homepage_title"
  get "pages/:id/sort/:new_position"                  => "pages#sort",            :as => :page_sort
  get "products/:id/sort/:new_position"               => "products#sort",         :as => :product_sort
  get "stay-connected"                                => "pages#connect"
  get "homepage1"                                     => "pages#homepage1"

  post "feedbacks/newsletter_signup" => "feedbacks#newsletter_signup", :as => :newsletter_signup

  get "products/:product_id/product_flavours/:id/sort/:new_position" => "product_flavours#sort", :as => :product_flavours_sort

  get "shopping_cart"                                 => "orders#show",                               :as => :current_order,  :id => "current"
  post "shopping_cart/add_discount"                   => "shopping_cart#add_discount",                :as => :add_discount
  get "shop/category/:slug"                           => "products#category",                         :as => :shop_category
  get "shop/categories"                               => "shopping_cart#categories",                  :as => :shop_categories
  get "shop/cart/:id"                                 => "shopping_cart#shopping_cart",               :as => :shop_cart
  post "shop/add_to_cart/:id"                         => "products#add_to_cart",                      :as => :add_product_to_cart
  get "shop/products/:slug"                           => "products#show",                             :as => :shop_product
  get "shop/empty_cart"                               => "shopping_cart#empty_cart",                  :as => :shop_empty_cart
  get "shop/checkout"                                 => "shopping_cart#checkout",                    :as => :shop_checkout
  get "shop/thankyou"                                 => "shopping_cart#thankyou",                    :as => :shop_thankyou
  get "shop/one_more_item/:id"                        => "shopping_cart#one_more_item",               :as => :shop_one_more_item
  get "shop/one_less_item/:id"                        => "shopping_cart#one_less_item",               :as => :shop_one_less_item
  get "shop/remove_item/:product_id/:option/:flavour" => "shopping_cart#remove_item",                 :as => :shop_remove_item
  post "shop/place_order"                             => "shopping_cart#place_order",                 :as => :shop_place_order
  post "shop/order_review_update_totals"              => "shopping_cart#order_review_update_totals",  :as => :order_review_update_totals
  get "shop/update_totals"                            => "shopping_cart#update_totals",               :as => :update_totals
  get "shop/submit_to_paypal/:id"                     => "shopping_cart#submit_to_paypal",            :as => :shop_submit_to_paypal

  resources :password_resets, :except => [:show, :index]
  resources :backgrounds
  resources :shipping_rates
  resources :discounts
  resources :documents
  resources :payment_notifications
  resources :line_items
  resources :orders
  resources :feedbacks
  resources :images do
    collection do
      get :browse
      post :upload
    end
  end
  resources :blog_categories
  resources :blog_posts
  resources :features do
    collection do
      put :update_left
      put :update_middle
      put :update_right
      get :edit_left
      get :edit_middle
      get :edit_right
    end
  end
  resources :pages do
    collection do
      get :edit_homepage_title
      put :update_homepage_title
    end
  end
  resources :product_types
  resources :products do
    collection do
      get :order
      put :sort
    end
    resources :product_flavours
  end
  resources :places
  resources :users
  resources :user_sessions

  get ":section_slug"             => "pages#show", :overview => true, :as => :show_section
  get ":section_slug/:page_slug"  => "pages#show",                    :as => :show_page

  root :to => "pages#homepage"

end

app/models/product.rb
class Product < ActiveRecord::Base
  MAX_PHOTO_SIZE = 6 # megabytes
  DEFAULT_PRICE = 15.99 # dollars
  DEFAULT_SIZE = 400 # grams
  OPTION_WHOLE_NAME = "Whole Bean"
  OPTION_WHOLE_URL = "whole-bean"
  OPTION_GROUND_NAME = "Ground"
  OPTION_GROUND_URL = "ground"
  OPTION_WHOLE_DECAF_NAME = "Whole Bean Natural Decaf"
  OPTION_WHOLE_DECAF_URL = "whole-bean-natural-decaf"
  OPTION_GROUND_DECAF_NAME = "Ground Natural Decaf"
  OPTION_GROUND_DECAF_URL = "ground-natural-decaf"
  OPTION_COFFEE_PODS_NAME = "Pods"
  OPTION_COFFEE_PODS_URL = "pods"

  #attr_protected :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at

  belongs_to :product_type
  has_and_belongs_to_many :pages
  has_and_belongs_to_many :discounts
  has_many :line_items
  has_many :product_flavours

  before_save :make_slug
  acts_as_list

  has_attached_file :photo,
    :path => ":rails_root/public/system/:attachment/:id/:style/:basename.:extension",
    :url => "/system/:attachment/:id/:style/:basename.:extension",
    :styles => {  :original =>      ["900>", :jpg],
                  :large =>         ["660", :jpg],
                  :medium =>        ["330", :jpg],
                  :small =>         ["184", :jpg],
                  :square =>        ["184x184#", :jpg],
                  :tiny =>          ["60", :jpg],
                  :tiny_square =>   ["60x60#", :jpg],
                  :thumb =>         ["30x30#", :jpg],
                  :shopping_cart => ["40x40#", :jpg],
                  :icon =>          ["32x32#", :jpg],
                  :featured =>      ["184x109#", :jpg] }

  validates_presence_of :name, :product_type_id
  validates_uniqueness_of :name
  validates_length_of :name, :minimum => 2
  validates :size, :numericality => { :greater_than => 0 }
  validates :acidity,       :numericality => { :greater_than => 0, :less_than => 10 }
  validates :roast,         :numericality => { :greater_than => 0, :less_than => 10 }
  validates :body_quality,  :numericality => { :greater_than => 0, :less_than => 10 }
  validates :price, :format => { :with => /\d+??(?:\.\d{0,2})?/ }, :numericality => { :greater_than => 0 }
  validates_attachment_content_type :photo, :content_type => [  "image/jpeg",
                                                                "image/gif",
                                                                "image/png",
                                                                "image/tiff",
                                                                "image/pjpeg",
                                                                "image/x-png" ]
  validates_attachment_size :photo, :less_than => MAX_PHOTO_SIZE.megabytes
  validates_attachment_presence :photo

  def body_name
    pq = ProductQuality.where(:kind => "body", :value => self.body_quality).first
    pq.blank? ? "None" : pq.name
  end

  def acidity_name
    pq = ProductQuality.where(:kind => "acidity", :value => self.acidity).first
    pq.blank? ? "None" : pq.name
  end

  def roast_name
    pq = ProductQuality.where(:kind => "roast", :value => self.roast).first
    pq.blank? ? "None" : pq.name
  end

  protected

  def make_slug
    self.slug = self.name.parameterize
  end

  def transliterate_file_name
    if photo_file_name
      extension = File.extname(photo_file_name).gsub(/^\.+/, "")
      filename = photo_file_name.gsub(/\.#{ extension }$/, "")
      self.photo.instance_write(:file_name, "#{ transliterate(filename) }.#{ transliterate(extension) }")
    end
  end

  def transliterate(string)
    s = string.downcase
    s = s.gsub(/'/, "")
    s = s.gsub(/[^A-Za-z0-9]+/, " ")
    s = s.strip
    s = s.gsub(/\ +/, "-")
    s
  end

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base
  has_many :products

  before_save :make_slug

  validates_presence_of :name
  validates_length_of :name, :minimum => 2

  protected

  def make_slug
    self.slug = self.name.parameterize
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_admin, :except => [:index, :show, :add_to_cart, :category, :categories]
  before_filter :get_product_types, :except => [:index, :show, :destroy, :order, :sort, :add_to_cart]
  before_filter :get_section
  #before_filter :user_country_code, :only => [:index, :show, :add_to_cart]
  #before_filter :estimated_shipping_price, :only => [:index, :show, :add_to_cart]
  #uses_tiny_mce :only => [:new, :create, :edit, :update]

  def index
    if current_user && current_user.is_admin?
      @products = Product.order(:position)
    else
      @products = Product.order(:position).where(:is_active => true, :is_special => false)
    end
    @page = Page.where(position: 1, section_id: @section.id).first
  end

  def category
    @product_type = ProductType.where(:slug => params[:slug]).first
    if current_user && current_user.is_admin?
      @products = @product_type.products.order(:position)
    else
      @products = @product_type.products.where(:is_active => true, :is_special => false).order(:position)
    end
    @page = Page.where(:position => 1, :section_id => @section.id).first
    render :index
  end

  def categories
  end

  def show
    index
    if params[:slug]
      @product = Product.where(:slug => params[:slug]).first
    else
      @product = Product.find(params[:id])
    end
    @client_country_code_temp = client_country_code

    if @product.blank? || (@product.is_active == false && !current_user)
      page_not_found
    end
  end

  def add_to_cart
    @product = Product.find(params[:id])
    if params[:product_flavour_slug]
      @product_flavour = ProductFlavour.where({ :slug => params[:product_flavour_slug] }).first
      @flavour_name = @product_flavour.slug
    elsif params[:product_flavour] # New alternative method of passing flavour param when using collection_select method.
      @product_flavour = ProductFlavour.where({ :slug => params[:product_flavour][:slug] }).first
      @flavour_name = @product_flavour.slug
    else
      @flavour_name = "none"
    end
    if params[:option_whole_quantity].to_i > 0
      @new_option_whole_item = @cart.add_cart_item(@product, params[:option_whole_quantity].to_i, Product::OPTION_WHOLE_URL, @flavour_name)
    end
    if params[:option_ground_quantity].to_i > 0
      @new_option_ground_item = @cart.add_cart_item(@product, params[:option_ground_quantity].to_i, Product::OPTION_GROUND_URL, @flavour_name)
    end
    if params[:option_whole_decaf_quantity].to_i > 0
      @new_option_whole_decaf_item = @cart.add_cart_item(@product, params[:option_whole_decaf_quantity].to_i, Product::OPTION_WHOLE_DECAF_URL, @flavour_name)
    end
    if params[:option_ground_decaf_quantity].to_i > 0
      @new_option_ground_decaf_item = @cart.add_cart_item(@product, params[:option_ground_decaf_quantity].to_i, Product::OPTION_GROUND_DECAF_URL, @flavour_name)
    end
    if params[:option_coffee_pods_quantity].to_i > 0
      @new_option_coffee_pods_item = @cart.add_cart_item(@product, params[:option_coffee_pods_quantity].to_i, Product::OPTION_COFFEE_PODS_URL, @flavour_name)
    end
    respond_to do |format|
      format.html { redirect_to_back(products_path) }
      format.js
    end
  end

  def order
    @products = Product.order(:position)
  end

  def sort
    product = Product.find(params[:id])
    product.insert_at(params[:new_position].to_i)
    render :nothing => true
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)

    if Product.count > 0
      last_product = Product.order(:position).last
      @product.position = last_product.position + 1
    else
      @product.position = 1
    end

    if @product.save
      redirect_to @product, :notice => 'Product was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product, :notice => 'Product was successfully updated.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to products_url
  end

  private

  def get_product_types
    @product_types = ProductType.order(:id)
  end

  def get_section
    @section = Section.where(slug: "shop").first
  end

  def product_params
    params.require(:product).permit(:name, :description, :body, :price,
      :is_active, :size, :option_ground, :option_ground_decaf,
      :option_whole, :option_whole_decaf, :option_coffee_pods,
      :acidity, :body_quality, :roast,
      :keywords, :product_type_id, :keywords, :position, :lists_all_flavours,
      :include_flavour_descriptions, :include_graphs, :per, :price_alt_txt,
      :out_of_stock, :is_special, :photo, :photo_file_name, :photo_content_type,
      :photo_file_size, :photo_updated_at)
  end

end

app/helpers/products_helper.rb
module ProductsHelper

  def product_container(position)
    if position == 0
      return "feature-left"
    elsif position == 1
      return "feature-middle"
    else
      return "feature-right"
    end
  end

  def product_quality_graph(value)
    graph =  "<div class='graph clearfix'>"
    (1..value).each do |i|
      graph += "<div class='solid'></div>"
    end
    ((value + 1)..9).each do |i|
      graph += "<div class='empty'></div>"
    end
    graph += "</div>"
    
    return graph
  end

  def product_flavour_descriptions(product)
    if product.product_flavours.size > 0
      descriptions = '<ul class="product-flavour-descriptions">'
      product.product_flavours.order(:position).each do |flavour|
        descriptions += '<li>'
        descriptions += "<b>#{ flavour.name }</b> "
        descriptions += flavour.description
        descriptions += '</li>'
      end
      descriptions += '</ul>'

      return descriptions
    end
  end

end

app/views/products/_add_to_cart.html.haml
= form_tag add_product_to_cart_path(@product), :remote => true, :class => "shop-form purchase", :id => "add-to-cart-form" do
  - if @product.lists_all_flavours
    %div{ :style => "padding-bottom: 20px;" }
      - @product_flavours = ProductFlavour.where(:product_id => @product.id).order(:position)
      =# select_tag "product_flavour_slug", options_from_collection_for_select(@product_flavours, "slug", "name"), :class => "product-flavour-select-button"
      = collection_select :product_flavour, :slug, @product_flavours, :slug, :name, { :disabled => lambda{ |flavour| flavour.out_of_stock } }, :class => 'product-flavour-select-button'
  %table#product-options
    - if @product.option_whole
      %tr
        %td.image= image_tag "icon_whole_bean.png", :size => "32x32", :alt => "Whole Bean"
        %td.description= Product::OPTION_WHOLE_NAME
        %td.input
          %input{ :type => "text", :value => 0, :maxlength => 3, :name => "option_whole_quantity", :id => "add-to-cart-option-whole-quantity" }
    - if @product.option_ground
      %tr
        %td.image= image_tag "icon_ground.png", :size => "32x32", :alt => "Ground"
        %td.description= Product::OPTION_GROUND_NAME
        %td.input
          %input{ :type => "text", :value => 0, :maxlength => 3, :name => "option_ground_quantity", :id => "add-to-cart-option-ground-quantity" }
    - if @product.option_whole_decaf
      %tr
        %td.image= image_tag "icon_whole_bean_decaf.png", :size => "32x32", :alt => "Natural Whole Bean Decaf"
        %td.description= Product::OPTION_WHOLE_DECAF_NAME
        %td.input
          %input{ :type => "text", :value => 0, :maxlength => 3, :name => "option_whole_decaf_quantity", :id => "add-to-cart-option-whole-decaf-quantity" }
    - if @product.option_ground_decaf
      %tr
        %td.image= image_tag "icon_ground_decaf.png", :size => "32x32", :alt => "Natural Ground Decaf"
        %td.description= Product::OPTION_GROUND_DECAF_NAME
        %td.input
          %input{ :type => "text", :value => 0, :maxlength => 3, :name => "option_ground_decaf_quantity", :id => "add-to-cart-option-ground-decaf-quantity" }
    - if @product.option_coffee_pods
      %tr
        %td.image= image_tag "icon_coffee_pod.png", :size => "32x32", :alt => "Coffee Pods"
        %td.description= Product::OPTION_COFFEE_PODS_NAME
        %td.input
          %input{ :type => "text", :value => 0, :maxlength => 3, :name => "option_coffee_pods_quantity", :id => "add-to-cart-option-coffee-pods-quantity" }
  = submit_tag "+ Add to Cart", :id => "add-to-cart-button"
  .loading
    Adding to cart. Please wait.

app/views/products/_form.html.haml
= simple_form_for @product, :html => { :multipart => true } do |f|
  = f.error_messages
  = f.input :name, :input_html => { :size => 20 }
  = f.input :description
  = f.input :price, :as => :string, :input_html => { :size => 4 }
  = f.input :size, :input_html => { :size => 4 }, :label => "Weight"
  = f.input :product_type_id,
    :collection => @product_types.collect { |pt| [pt.name, pt.id] },
    :prompt => "- select a type -",
    :as => :radio_buttons
  = f.input :body, :input_html => { :class => "tinymce medium" }, :label => "Details", :required => false
  .input
    %label
      Options
    .checkbox-collection
      = f.check_box :option_ground
      Ground?
      &nbsp;&nbsp;
      = f.check_box :option_whole
      Whole Bean?
      &nbsp;&nbsp;
      = f.check_box :option_ground_decaf
      Ground Decaf?
      &nbsp;&nbsp;
      = f.check_box :option_whole_decaf
      Whole Bean Decaf?
      = f.check_box :option_coffee_pods
      Coffee Pods?
  = f.input :roast, :collection => 1..9, :as => :radio_buttons
  = f.input :body_quality, :label => "Body", :collection => 1..9, :as => :radio_buttons
  = f.input :acidity, :collection => 1..9, :as => :radio_buttons
  = f.input :photo, :label => "Image", :required => false
  - if @product.photo.exists?
    .preview-image
      = image_tag @product.photo.url(:square)
  = f.input :lists_all_flavours, :label => "Include option to choose from list of flavours?"
  = f.input :include_flavour_descriptions, :label => "Auto-generate descriptions from flavour list?"
  = f.input :include_graphs, :label => "Show roast, body, and acidity graphs?"
  = f.input :per, :label => "Unit text", :hint => "Text appearing after product price (e.g., 'per pkg.')"
  = f.input :price_alt_txt, :label => "Alt text", :hint => "Optional text appearing under product price (e.g., '(comes in 456g packages)')"
  = f.input :keywords
  = f.input :is_active, :label => "Publicly viewable?"
  = f.input :out_of_stock, :label => "Out of stock?"
  = f.input :is_special, :label => "Is this a special hidden product?"
  = f.button :submit

= tinymce

app/views/products/_other_products.html.haml
/ = link_to "Other Products", "#", :id => "other-products-toggle"
%b Other Products
%br
%ul#other-products.clearfix
  - @products.each do |product|
    - unless product == @product
      - product_roast = ProductQuality.where(:kind => "roast", :value => product.roast).first
      %li= link_to image_tag(product.photo.url(:icon), :size => "32x32", :alt => product.name),
        product_path(product),
        "data-name" => product.name,
        "data-roast" => product_roast.name,
        :id => "product-#{ product.id }"
#other-products-caption
  %h3
  .roast

app/views/products/edit.html.haml
- content_for :title do
  Editing Product

%div{ :style => "margin-bottom: 20px;" }
  %b= "http://muskokaroastery.com/shop/products/#{ @product.slug }"
  
= render 'form'

- content_for :sidebar do
  %p= link_to "Preview Product", @product, :class => "feature-button"
  %br
  %p= link_to "Back to Product Listing", products_path

app/views/products/index.html.haml
- content_for :title do
  - if @product_type
    = @product_type.name
  - else
    = @page.name

- unless @product_type
  = image_tag "shop_packagingComposition.png", :alt => "Our products", class: 'main-product-image'

#intro
  =raw @page.intro

=raw @page.body


%hr{ :style => "margin-bottom: 40px;" }

- number_of_products = @products.length - 1

- if @products.length == 0
  %b Sorry, we currently do not have any products in this category. Try viewing all the products on the
  = link_to "main shop page", shop_path
- else
  - (0..number_of_products).step(3) do |i|
    .clearfix.product-list-top
      - for j in 0..2
        - product = @products[i + j]
        - unless product.blank?
          %div{ :class => "#{ product_container(j) }" }
            = link_to image_tag(product.photo.url(:square), :size => "184x184", :border => 0, :alt => product.name, :class => "featured-image"), shop_product_path(product.slug)
            %h2
              = "*" if product.is_active == false || product.is_special
              = product.name
            %p
              %b.dark= product.roast_name.upcase
              = product.description
            %p= link_to "See Details", shop_product_path(product.slug), :class => "feature-button"

    / .clearfix.product-list-bottom
    /   - for j in 0..2
    /     - product = @products[i + j]
    /     - unless product.blank?
    /       %div{ :class => "#{ product_container(j) }" }
    /         %p= link_to "See Details", shop_product_path(product.slug), :class => "feature-button"

- content_for :sidebar do
  #shopping-cart-container
    = render :partial => "shopping_cart/small_cart"
  - if current_user && current_user.is_admin?
    %hr
    %p= link_to 'New Product', new_product_path, :class => "feature-button"
    %br
    %p= link_to "Change Order", order_products_path
    %p= link_to "Edit Page Details", edit_page_path(@page)
    / %p= link_to "Manage Flavours", product_flavours_path

= render "floodlight_tags/shop"

app/views/products/new.html.haml
- content_for :title do
  New Product

= render 'form'

- content_for :sidebar do
  %p= link_to "Back to Product List", products_path

app/views/products/order.html.haml
- content_for :title do
  Change Product Order

%ul.sortable-products
  - @products.each do |product|
    %li{ "data-product" => product.id }
      %span.handle
      %span.product-order-name
        - unless product.is_active
          *
        %b= product.name
      %span.product-order-type
        = "(#{ product.product_type.name })"

- content_for :sidebar do
  %p= link_to "Back to Product List", products_path

app/views/products/show.html.haml
- content_for :title do
  = @product.name

#product-basics
  = image_tag @product.photo.url(:square), :size => "184x184", :alt => @product.name + " illutration", :class => "featured-image"

  #product-price
    %h1
      = number_to_currency(@product.price, :unit => "$", :separator => ".", :precision => 2)
      #product-price-description
        = @product.per
        / per pkg.
    %p
      = "(#{ @product.price_alt_txt })"
      / (comes in
      / %strong= @product.size.to_s + "g"
      / packages)

  #product-purchase
    - if @product.out_of_stock
      %h2 Out of Stock
      %p
        We're sorry, but this product is currently out of stock. Please check
        back later to see when it becomes available again.
    - else
      %h2 Purchase
      %p
        Select type and quantity, then add to your cart.

      #add-to-cart-form-container
        = render :partial => "add_to_cart", :locals => { :product => @product }

#product-details
  #intro
    =simple_format @product.description

  #product-body
    =raw @product.body

    / Insert optional auto-descriptions here for any product *options* or *flavours* so there's no need to re-type anything.
    - if @product.include_flavour_descriptions
      =raw product_flavour_descriptions(@product)

  - if @product.include_graphs
    #product-graphs
      .quality
        %h3 Roast
        .name= @product.roast_name
        =raw product_quality_graph(@product.roast)
      .quality
        %h3 Body
        .name= @product.body_name
        =raw product_quality_graph(@product.body_quality)
      .quality
        %h3 Acidity
        .name= @product.acidity_name
        =raw product_quality_graph(@product.acidity)

  %nav#product-alt-nav
    = render :partial => "other_products"

- content_for :sidebar do
  - if controller.action_name != "checkout"
    #shopping-cart-container
      = render :partial => "shopping_cart/small_cart"
  - if current_user && current_user.is_admin?
    %hr
    %p= link_to "Edit Product", edit_product_path(@product), :class => "feature-button"
    %p= link_to "Manage Flavours", product_product_flavours_path(@product)
    %br
    %p= link_to "Back to Product List", products_path
    / %p= link_to "Destroy", product_path(@product), :confirm => "Are you sure?", :method => :delete

- unless @product.description.blank?
  - content_for :description do
    = @product.description
- unless @product.keywords.blank?
  - content_for :keywords do
    = @product.keywords

- content_for :scripts do
  = javascript_include_tag :product_details
  -# = include_javascripts :validate_add_to_cart_min